package main

//
// a word-count application "plugin" for MapReduce.
//
// go build -buildmode=plugin wc.go
//

import "6.824/mr"
import "unicode"
import "strings"
import "strconv"

//
// The map function is called once for each file of input. The first
// argument is the name of the input file, and the second is the
// file's complete contents. You should ignore the input file name,
// and look only at the contents argument. The return value is a slice
// of key/value pairs.
//

// Map函数对每个输入文件调用一次。第一个参数是输入文件名，第二个是文件的完整内容。
// 应忽略文件名，只关注内容参数。返回值是键值对切片。
func Map(filename string, contents string) []mr.KeyValue {
	// function to detect word separators.
	// 定义单词分隔符检测函数（非字母字符视为分隔符
	ff := func(r rune) bool { return !unicode.IsLetter(r) }

	// split contents into an array of words.
	// 将文本内容按分隔符拆分为单词数组
	words := strings.FieldsFunc(contents, ff)

	// 生成中间键值对：每个单词对应计数值"1"
	kva := []mr.KeyValue{}
	for _, w := range words {
		kv := mr.KeyValue{w, "1"}
		kva = append(kva, kv)
	}
	return kva
}

//
// The reduce function is called once for each key generated by the
// map tasks, with a list of all the values created for that key by
// any map task.
//

// Reduce函数对Map任务生成的每个键调用一次，传入该键对应的所有值列表。
func Reduce(key string, values []string) string {
	// return the number of occurrences of this word.
	// 返回该单词的出现次数（值列表的长度即为次数）
	return strconv.Itoa(len(values))
}
